version: '3.9'

networks:
  my-network:

services:
  nginx-proxy:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./devops/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - 'my-network'

  apache-web:
    image: httpd  # this will use httpd:latest
    container_name: apache
    volumes:
      - ./devops/conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./app:/var/www/html/:rw
    networks:
      - 'my-network'

  php-fpm:
    tty: true # Enables debugging capabilities when attached to this container.
    image: php:7.2-fpm
    container_name: php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html/:rw
    networks:
      - 'my-network'

  mariadb:
    image: mariadb:10.4.10-bionic
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql:rw'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MYSQL_DATABASE: app
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    networks:
      - 'my-network'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8181:80'
    environment:
      - 'PMA_HOST=mariaDB'
    depends_on:
      - 'mariadb'
    networks:
      - 'my-network'

  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: node:fermium-stretch
    container_name: nodejs
    # command: sh -c 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './app:/usr/src/app:rw'
    networks:
      - 'my-network'
  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp server
    networks:
      - 'my-network'

volumes:
  mariadb_data: